### ISSUE TITLE
data.gov interview

### ISSUE THREAD

**Issue by anthonygarvan** [18F/data-federation-report#2]
[ First a reminder: Notes & Report will be public ]
## What is data.gov, in your own words?
It's the federal government open data site, in the name it's a meta data catalog to make it easy to discover and use data made open by agencies of the federal government (note: includes some non-open data and state & local). Also the manifestation of an internal gov-wide open data policy.

## What was impetus or driving force for this effort: policy, user needs, etc (perhaps after the first question)
Geospatial efforts (geoplatform 1) had been an effort to make gov wide catalog of geospatial efforts, thinks it goes back to OMB 16, from effort to coordinate geospatial data from wartime. Existed before 2009. Before 2009 there were agencies that had data on websites. Presidential memo on openness and transparency in government (broader than just data), also OMB policy on open government that required the standup of a data site, stood up in a couple months in May 2009. Original policy required 3 data sets, received datasets and put in first version. From 2009 - 2013 there was steady growth in data.gov, many initiatives blended into data.gov. Continual effort with monthly working group. Many open data efforts included clauses to include data in data.gov. 2013 memo to include open data w/ accompanying OMB policy, states that agencies maintain open data catalog in standard file format on their server. Before 2013 they were operating as a centralized platform. Allows agencies to take advantage of inventories they already have, just automatically reformat into proper metadata schema. Allows agencies to integrate their inventories, acknowledging that there were a lot of publishing efforts going on, just not a great way to catalog. Diversity in capabilities prior to effort. 

## in building current data.gov, what were the biggest challenges, and what went smoothly?

"took a while for agencies to get on board as to whether it was a good thing" "Some agencies by nature are going to be more hesitant about participating in something that means releasing more information" "Some risk aversion" concern that they will be exposed to people finding fault with data. Concern about judgement from OMB. Some agencies it was a challenge to find tools & resources to comply with this. Made inventory.data.gov in order to manage metadata, add / remove datasets etc. Very helpful for agencies that didn't have an inventory service already. Transition to new policy and new architecture took some time, there were some rough spots. e.g., making sure schema was very well documented, mechanisms to validate. Initial schema was designed to align with international schema standard, second iteration of refinement implemented final standard. Had to take an iterative design ethos- "just do it" then iron out the kinks. How to set expectations? some highlights - no change management timeline around schema, maybe could have been more communication around changes. should have been an official beta. 

## Could you describe the data aggregation and distribution processes of data.gov?
For larger agencies, they work on this as part of the OMB policy they are required to follow. They are part of the open data community, people are responsible at agencies have regular meetings with OMB & one another. Have community discussing the nuts & bolts. For smaller agencies not required, they have been opting in and following schema. To a certain extend non-federal also provide minimal essential data (~50 participants). Policy asks agencies to inventory all data sets, but is pretty broad, includes non-public and restricted, inventory must follow metadata schema documented on project open data, put it all on data.json file which is hosted on website. Each endpoint is registered on data.gov, harvester checks every 24 hours, if changed then it processes and adds / removes / updates entries. btw, there is a parallel process for geospatial standards. Originally more distinction between public and private datasets.

## Why did you choose this architecture or process. Were others tried, etc (after the "data aggregation/distribution" question)
some things came up - metadata vs hosting data. not really set up to host lots of data for agencies on their behalf. policy & process requires enterprise wide inventory, sometimes smaller entities (e.g. departments) want to publish their data. big departments with independent fiefdoms. easier for some than others. Sometimes easier for agencies that don't have a big history / legacy systems. Modernizing harder.

## What are the political and organizational dynamics of collecting this data?
[ skipped, already covered, low on time ] 

## Who were the relevant stakeholders for this project, how were they identified and convened? 
try to have minimum number of people from each department. 

## Is there anyone else I should speak with to better understand data.gov?
might be nice to hear from an agency lead. might be nice to talk with federal geospatial group.

**Comment by hkdctol** [comment]
Draft notes seem fine. On the stakeholders: EOP as the origin of the relevant executive orders and OMB policies, OMB staff with open data responsibilities, GSA as the implementer, the federal agencies, outside interest/advocacy groups in open data and open government, and the public. As far as identifying them, it was pretty apparent from the beginning since the origin was EOP and federal agencies are the subject of the policy, and overall there was a collaborative approach to including outside groups--for instance in both open government and open data efforts there have been regular meetings (quarterly) where outside interest groups have been invited to attend.  Also stakeholders - Congress, particularly as there is pending legislation to make the open data policy requirements statutory, as well as GAO - open data was one of the areas that they studied and issued a report on earlier this year.
