### ISSUE TITLE
code.gov interview

### ISSUE THREAD

**Issue by anthonygarvan** [18F/data-federation-report#3]
[ First a reminder: Notes & Report will be public ]
[ Second, what is this effort all about? What am I looking to get out of it? ]
[ Third, any questions before we get started? ]

## What is X, in your own words?
Code.gov is the central place to see America's code. It is also the official public implementation of the source code policy.

## What was impetus or driving force for this effort: policy, user needs, etc (perhaps after the first question)
"The impetus to create code.gov derives from policy." now the project has evolved, and there are a whole bunch of other reasons why, but policy has always been the main focus, and how to stay true to that policy. 

## in building code.gov, what were the biggest challenges, and what went smoothly?
At the start, the biggest hurdle was actually getting agencies to come on board. Actually getting them to fill the code.json, helping them out.. explaining the policy, getting them to understand the requirements. Getting agencies to understand we're here to help. Project was always meant to follow a lean / agile management style. Challenge: How to setup code.gov as quickly as possible while still serving users & policy goals? Scoured github for open source code for agencies. Then: how do we evolve what was already done, in the quickest possible way within the same constraints, within the government framework (ATO, technology, etc)? What compromises should we make to get this out the door as quick as possible, but still have it be what our clients need and what policy dictates? e.g., need to expand beyond static site, so we need infrastructure. Communicating through github, building community is a current priority, getting buy-in / ownership from agencies as well as public. What went well? The initial site (from 1 year ago), got it pretty well for a first try. It was a site they put out in a hurry, very much an MVP, no idea what the community response would be. "[just] ship it!" When they went out to oscon / put it on hackernews, had 100k views. NB: it was on federalist. Good infrastructure decision to start with static site. Shipped before full compliance. Gave them a sense of who the audience was going to be. got feedback from policy / community. Another challenge: from an agency perspective, communicating benefits / incentives for agencies is a challenge. (e.g., why should we do this, our stuff is already on github? Or, why open source our code?) Challenge is to get agency code in one place. Challenge at the program level, not always the product / website level. "not so much the technology, it's the people / process."

## Could you describe the data aggregation and distribution processes of code.gov?
"code.gov is a huge ETL project" policy actually defines that agencies must have a code.json on their site (most have in their root directory). Code.gov fetches all the code.json of all the participating agencies, transforms it into ways it can be served on the site." "Search is an important thing for code.gov.. that's why we load everything into elasticsearch." Right now, loading everything into static site. Code.gov is only distribution model. 

## Why did you choose this architecture or process. Were others tried, etc (after the "data aggregation/distribution" question)
[skipping]

## What are the political and organizational dynamics of collecting this data?
"From what I've seen, there's been no need to strong-arm anybody into this policy" "No need to make a huge law.. policy speaks for itself." "Major issue, as with everything that relates to people, is effort and time" "[agencies] may not actively maintain it." "Challenge is to keep this in mind as something that is relevant to something that they should keep doing" "Dynamic hasn't been very difficult talking to agencies." "What we're seeing across government is that it's split into thirds, 1/3 that has no policies relevant, 1/3 that have portions, 1/3 that already have full policy". Some folks nervous about making anything public. Would be helpful to get into a law long-term. The more we can get it solidified into law [the better]. Really helpful to have a few shining examples you can show other agencies as an example. "Look at [nasa , GSA, etc], clone these repos, take these steps etc." 

## Is there anyone else I should speak with to better understand X?

**Comment by froi** [comment]
Hi @anthonygarvan 

> Code.gov is the central place to see America's code. It is also the official public implementation of the source code policy.

Code.gov is the central place to see America's code. It is also the official public implementation of the [Federal Source Code Policy](https://code.gov/#/policy-guide/policy/introduction).
