### ISSUE TITLE
As a team member, I want a couple good use cases we can use to better understand how the ingest mechanism might work and who would benefit from it. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/data-federation-report#32]
## Goal
Let’s identify a few top use case candidates that we can work with.  Two stages - first, let’s figure out the thing we’re going to work on while we line up the ideal use case.  The program code thing is basically ready to go, and we do have historical data from that, so we’d have no dependencies there. We could go with that initially as Kathryn’s loading it in the ingest mechanism.  Or, we could just build the mechanism.  
  
## Acceptance criteria
- [x] Keep on top of meetings / email chains (currently ongoing threads with OMB / DHS / USDA)
- [x] We've decided to keep it free- running until we get something juicier to work with. 
- [x] Select the first use case!  
- [x] Set up a working session to pick first use case! (Chris to schedule)
## Once use case is selected
- [x] Make sure we communicate this to the partner
- [x] Get relevant documents / data / process established with the partner
- [x] Identify the first “prototype” thing we want to build / test. 
- [x] Keep on top of meetings / email chains (currently ongoing threads)
## Finally, track burn rates to make sure we’ll do what we need to do
- [x] Weekly burn rate updates from 10x

**Comment by philipashlock** [comment]
here's the [google doc](https://docs.google.com/document/d/1WjcbDxzf5nlEKIdwjc13ugMoLPjQ0Ti4RBJrnl_lO9M/edit#) currently being used to track candidates but we should get in the habit of asking those with case studies if they mind us publicly tracking them here since that would be the ideal.
