### ISSUE TITLE
Review and respond to the open data standards draft guide. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/data-federation-report#33]
## Acceptance criteria
- [x] Respond to open data standards draft guide (Chris / Phil)
Feedback by April 6th, and / or being aware of it to inform/structure this work (and avoid duplication).

**Comment by philipashlock** [comment]
You can channel feedback to me by email if you have anything, but this is not yet meant to be shared publicly.

**Comment by OpenGlobe** [comment]
A few comments are here: https://docs.google.com/document/d/1UgQZhDaAM1PSOhsLRZVjbFgHMUylGcjJX86nYFYcILg/edit
