### ISSUE TITLE
As a user of the API I want the ability to use non-ordered JSON values and / or send one record at a time without headers.  

### ISSUE THREAD

**Issue by OpenGlobe** [18F/data-federation-report#68]
## User story
As a user of the API I want the ability to use non-ordered JSON values and / or send one record at a time without headers.  
  
## Acceptance criteria
- [x] Records can be sent in different orders
- [x] Records can be send without headers

**Comment by Jkrzy** [comment]
Initial functionality for validation of incoming JSON via API is in place: https://github.com/18F/django-data-ingest/pull/3

Users are able to submit an array of 1-N JSON objects containing the data to be validated. JSON object structure is 
```
{
"COLUMN_NAME": "VALUE",
...
}
```
