### ISSUE TITLE
As a developer I want a set of tests so I can check my work as I go. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/data-federation-report#69]
## User story
As a developer I want a set of tests so I can check my work as I go. 

## Acceptance criteria
- [x] Establish test suite for django-data-ingest (Joe)
- [x] Doesn’t appear to be one now, if implementation / features are necessary, stuff like this would be really helpful.

**Comment by Jkrzy** [comment]
Test suite established here: https://github.com/18F/django-data-ingest/pull/5

Includes unit test runner, python code linting, static security analysis, and code coverage metrics run by CircleCI on each pull request.
