### ISSUE TITLE
Research: Google Transit Feed Specification

### ISSUE THREAD

**Issue by anthonygarvan** [18F/data-federation-report#8]
- https://la.streetsblog.org/2010/01/08/how-google-and-portland%E2%80%99s-trimet-set-the-standard-for-open-transit-data/
- https://en.wikipedia.org/wiki/General_Transit_Feed_Specification

Note transit feed spec is not machine readable. Just thorough description of files & data required.

**Comment by philipashlock** [comment]
I can queue up some points of contact for this if we want to do direct interviews.

**Comment by anthonygarvan** [comment]
@philipashlock that would be great
